### ISSUE TITLE
Package support check

### ISSUE THREAD

**Issue by thornjad** [Raindeer44/clear-night-ui#10]

**Comment by thornjad** [comment]
Autocomplete-plus is good

**Comment by thornjad** [comment]
Build is good

**Comment by thornjad** [comment]
Color Picker is good

**Comment by thornjad** [comment]
Deprecation Cop is good

**Comment by thornjad** [comment]
Expose has issues. Need to reduce the box shadow. Also there seem to be lines at the top of the screen.

![selection_014](https://cloud.githubusercontent.com/assets/17414927/23009528/0d670c08-f3dc-11e6-877a-0ee2c657d250.png)

Also possibly look into moving "settings" and "close" icons to right side like in Expose's README preview:

![Expose](https://i.github-camo.com/ebe00b0f6d52cf01dba5fd0a0ec3ae861222c4a3/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d726f64616c67616172642f61746f6d2d6578706f73652f6d61737465722f73637265656e73686f74732f707265766965772e706e67)

**Comment by thornjad** [comment]
Find and replace is good. It's gotten a lot of attention in this update.

**Comment by thornjad** [comment]
Imdone looks good. Not doing extensive testing because I don't want all my `TODO`s to change.

**Comment by thornjad** [comment]
Markdown Preview: need to make preformatted text color darker.

![selection_015](https://cloud.githubusercontent.com/assets/17414927/23009661/e143c7fa-f3dc-11e6-99a9-14d84b90e1da.png)

**Comment by thornjad** [comment]
Minimap is good

**Comment by thornjad** [comment]
Project Find: I can't actually find what package this means. This is styling coming from Glacier Dark UI and doesn't reference a url or anything.

**Comment by thornjad** [comment]
Project Manager is good

**Comment by thornjad** [comment]
Script has some alignment issues. Labels and input are overlapping:

![selection_017](https://cloud.githubusercontent.com/assets/17414927/23009947/78b30988-f3de-11e6-8854-ac416358f978.png)

**Comment by thornjad** [comment]
Time Cop is good

**Comment by thornjad** [comment]
Tool-bar:

The actual toolbar maybe should have level-1-color background.

Testing with tool-bar-main it looks like the shadow behind pop-up text is way too large. Can't get a picture for this one. Didn't realize this is a problem all over Atom.

**Comment by thornjad** [comment]
The discovery of the shadow bug has moved to #13

**Comment by thornjad** [comment]
# Summary

## Packages with issues

1. ~~Expose~~
2. ~~Markdown Preview~~
3. ~~Script~~
4. ~~Tool-bar~~

**Comment by Raindeer44** [comment]
Not going to fix Expose gear and x icons. Not worth it right now.

**Comment by thornjad** [comment]
I got the Expose buttons as big as I want them, but they're not centered in their button boxes. When hovering over them, this becomes annoyingly obvious.

**Comment by thornjad** [comment]
Expose is fixed.

**Comment by thornjad** [comment]
Markdown Preview is fixed

**Comment by thornjad** [comment]
Script is fixed, but borders around the input boxes would be nice.

**Comment by thornjad** [comment]
Tool-bar is fixed

**Comment by thornjad** [comment]
Moving script comment to #16

**Comment by thornjad** [comment]
That completes the package support styling check.
