### ISSUE TITLE
Wrap guide is too dark

### ISSUE THREAD

**Issue by thornjad** [Raindeer44/clear-night-ui#22]
It appears to be black maybe? It's too dark to be comfortably seen.

**Comment by delta-one** [comment]
Yeah, you need magnifying glasses to see it. You can only see it, when you mark text.

**Comment by thornjad** [comment]
Found the bug, it appears to have been an interesting interaction with Atom's built in styling. Nothing a handy-dandy `!important` can't fix.

I'll publish the update after I try fixing some of these other issues.
