### ISSUE TITLE
Thick border in restart-dialog

### ISSUE THREAD

**Issue by delta-one** [Raindeer44/clear-night-ui#39]
I'm using the Clear Night together with the Clear Night Syntax theme and the restart-dialog (after having updated a package) has very thick borders around the versions. I don't think it's supposed to look that way.

**Screenshots and GIFs**

![Thick borders](https://i.imgur.com/MMsvm4h.png)

**Clear Night UI version:** 1.3.10

**Atom version:** 1.25

**OS and version:** Debian SID

**Comment by thornjad** [comment]
Sorry I didn't see this sooner, but I'm getting a fix in now.
